/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Model.Koneksi;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author Bryan
 */
public class Dashboard extends javax.swing.JFrame {
    Connection con; // mendeklarasikan dan membuat variabel koneksi
    Statement stat; // mendeklarasikan dan membuat variabel statement
    ResultSet rs; // mendeklarasikan dan membuat variabel resultset
    String sql; // mendeklarasikan dan membuat variabel String
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        Koneksi DB = new Koneksi(); // membuat objek dari kelas koneksi
        DB.config(); // memanggil kelas konfik dengan objek DB
        con = DB.con; // memasukan koneksi dengan koneksi milik DB
        stat = (Statement) DB.stm; // memasukan statement dengan statement milik DB
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        identitas = new javax.swing.JButton();
        satuan = new javax.swing.JButton();
        databarang = new javax.swing.JButton();
        user = new javax.swing.JButton();
        search = new javax.swing.JButton();
        print = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(47, 143, 157));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(59, 172, 182));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(130, 219, 216));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 68)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DASHBOARD");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 430, 100));

        identitas.setBackground(new java.awt.Color(59, 172, 182));
        identitas.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        identitas.setForeground(new java.awt.Color(255, 255, 255));
        identitas.setText("About Us");
        identitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identitasActionPerformed(evt);
            }
        });
        jPanel3.add(identitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 200, 60));

        satuan.setBackground(new java.awt.Color(59, 172, 182));
        satuan.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        satuan.setForeground(new java.awt.Color(255, 255, 255));
        satuan.setText("Kode Satuan");
        satuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuanActionPerformed(evt);
            }
        });
        jPanel3.add(satuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 200, 60));

        databarang.setBackground(new java.awt.Color(59, 172, 182));
        databarang.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        databarang.setForeground(new java.awt.Color(255, 255, 255));
        databarang.setText("Data barang");
        databarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databarangActionPerformed(evt);
            }
        });
        jPanel3.add(databarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 200, 60));

        user.setBackground(new java.awt.Color(59, 172, 182));
        user.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setText("User Information");
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        jPanel3.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 200, 60));

        search.setBackground(new java.awt.Color(59, 172, 182));
        search.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("Pencarian Barang");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel3.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 200, 60));

        print.setBackground(new java.awt.Color(59, 172, 182));
        print.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        print.setForeground(new java.awt.Color(255, 255, 255));
        print.setText("Print Report");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel3.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 200, 60));

        exitbtn.setBackground(new java.awt.Color(59, 172, 182));
        exitbtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        exitbtn.setForeground(new java.awt.Color(255, 255, 255));
        exitbtn.setText("Logout");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        jPanel3.add(exitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 140, 60));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 850, 540));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 890, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void identitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identitasActionPerformed
        new Identitas().setVisible(true); // memanggil kelas Identitas untuk ditampilkan 
        dispose(); // menutup jframe Dashboard
    }//GEN-LAST:event_identitasActionPerformed

    private void satuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuanActionPerformed
        new SatuanBarang().setVisible(true); // memanggil kelas SatuanBarang untuk ditampilkan 
        dispose(); // menutup jframe Dashboard
    }//GEN-LAST:event_satuanActionPerformed

    private void databarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databarangActionPerformed
        new DataBarang().setVisible(true); // memanggil kelas DataBarang untuk ditampilkan 
        dispose(); // menutup jframe Dashboard
    }//GEN-LAST:event_databarangActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        new Pengguna().setVisible(true); // memanggil kelas Pengguna untuk ditampilkan 
        dispose(); // menutup jframe Dashboard
    }//GEN-LAST:event_userActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        new TampilBarang().setVisible(true); // memanggil kelas TampilBarang untuk ditampilkan 
        dispose(); // menutup jframe Dashboard
    }//GEN-LAST:event_searchActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        try {
            con.createStatement().executeUpdate("DELETE FROM `uas32210021`.`report`"); // membuat button print menghapus table database report
            con.createStatement().executeUpdate("DELETE FROM `uas32210021`.`grand`"); // membuat button print menghapus table database grand
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage()); // menampilkan message box
        }
        new report().setVisible(true); // memanggil kelas report untuk ditampilkan 
        dispose(); // menutup jframe dashboard
    }//GEN-LAST:event_printActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        new Menu().setVisible(true); // memanggil kelas Menu untuk ditampilkan
        dispose(); // menutup jframe dashboard
    }//GEN-LAST:event_exitbtnActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Dimension posisi = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (posisi.width - this.getWidth())/2;
        int y = (posisi.height - this.getHeight())/2;
        this.setLocation(x, y);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton databarang;
    private javax.swing.JButton exitbtn;
    private javax.swing.JButton identitas;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton print;
    private javax.swing.JButton satuan;
    private javax.swing.JButton search;
    private javax.swing.JButton user;
    // End of variables declaration//GEN-END:variables
}
