/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Model.Koneksi;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author Bryan
 */
public class report extends javax.swing.JFrame {
    Connection con;
       Statement stat;
       ResultSet rs;
       String sql;
       DefaultTableModel model;
    /**
     * Creates new form report
     */
    public report() {
        initComponents();
        Koneksi DB = new Koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        String [] judul = {"Kode", "Nama Barang", "Kode Satuan", "Satuan", "Harga Beli", "Harga Jual", "Quantity", "Diskon", "Total Harga Jual", "Total Harga Beli"};
        model = new DefaultTableModel(judul,0);
        tabelakhir.setModel(model);
        showdat();
        showprice();
    }
    
    private void showdat(){
        int row = tabelakhir.getRowCount();
        for(int i=0; i<row;i++){
            model.removeRow(0);
        }
        try{
            sql = "SELECT * FROM tbdatabrg";
            rs = stat.executeQuery(sql);
            while(rs.next()){
               double hitungjual = (Double.parseDouble(rs.getString(5)) * 0.2) + Double.parseDouble(rs.getString(5));
               String hargajual = String.valueOf(hitungjual);
               double diskon = Double.parseDouble(rs.getString(5)) * 0.1;
               String txtdiskon = String.valueOf(diskon);
               double totaljual = Double.parseDouble(rs.getString(6)) * hitungjual;
               String txttotaljual = String.valueOf(totaljual);
               double totalbeli = Double.parseDouble(rs.getString(6)) * Double.parseDouble(rs.getString(5)) - diskon;
               String txttotalbeli = String.valueOf(totalbeli);
               String data []= {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), hargajual, rs.getString(6), txtdiskon, txttotaljual, txttotalbeli};
               model.addRow(data);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    private void showprice(){
        int row = tabelakhir.getRowCount();
        double totalhargabeli = 0;
        double totalhargajual = 0;
        
        for(int i=0; i<row;i++){
            totalhargajual = totalhargajual + Double.parseDouble((String) model.getValueAt(i, 8));
        }
        
        for(int i=0; i<row;i++){
            totalhargabeli = totalhargabeli + Double.parseDouble((String) model.getValueAt(i, 9));
        }
        
        grandjual.setText(String.valueOf(totalhargajual));
        grandbeli.setText(String.valueOf(totalhargabeli));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        searchbtn = new javax.swing.JButton();
        cetakbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelakhir = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        sampekode = new javax.swing.JTextField();
        grandbeli = new javax.swing.JTextField();
        inputkode = new javax.swing.JTextField();
        grandjual = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        back1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(47, 143, 157));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(59, 172, 182));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(130, 219, 216));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 68)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CETAK DATA");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, 420, 100));

        searchbtn.setBackground(new java.awt.Color(59, 172, 182));
        searchbtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        searchbtn.setForeground(new java.awt.Color(255, 255, 255));
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        jPanel3.add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 110, 50));

        cetakbtn.setBackground(new java.awt.Color(59, 172, 182));
        cetakbtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cetakbtn.setForeground(new java.awt.Color(255, 255, 255));
        cetakbtn.setText("cetak");
        cetakbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakbtnActionPerformed(evt);
            }
        });
        jPanel3.add(cetakbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 490, 110, 50));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 430, 60, 30));

        tabelakhir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama Barang", "Kode Satuan", "Satuan", "Harga Beli", "Harga Jual", "Quantity", "Diskon", "Total Harga Jual", "Total Harga Beli"
            }
        ));
        jScrollPane1.setViewportView(tabelakhir);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 1140, 210));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sampai Data Kode");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 190, 30));
        jPanel3.add(sampekode, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 180, 30));
        jPanel3.add(grandbeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 430, 130, 30));
        jPanel3.add(inputkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 180, 30));
        jPanel3.add(grandjual, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 430, 130, 30));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tampilkan Data Dari Kode");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 230, 40));

        back1.setBackground(new java.awt.Color(59, 172, 182));
        back1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        back1.setForeground(new java.awt.Color(255, 255, 255));
        back1.setText("back");
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });
        jPanel3.add(back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 110, 50));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1200, 590));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1240, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1282, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        String cari = inputkode.getText();
        String sampe = sampekode.getText();
        int row = tabelakhir.getRowCount();
        for(int i=0; i<row;i++){
            model.removeRow(0);
        }
        try{
            sql = "SELECT * FROM tbdatabrg" ;
            rs = stat.executeQuery(sql);
            if(inputkode.getText().equals("") || sampekode.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Data Masih Kosong");
                showdat();
            }else if(inputkode.getText().equals(sampekode.getText())){
               while(rs.next()){
               double hitungjual = (Double.parseDouble(rs.getString(5)) * 0.2) + Double.parseDouble(rs.getString(5));
               String hargajual = String.valueOf(hitungjual);
               double diskon = Double.parseDouble(rs.getString(5)) * 0.1;
               String txtdiskon = String.valueOf(diskon);
               double totaljual = Double.parseDouble(rs.getString(6)) * hitungjual;
               String txttotaljual = String.valueOf(totaljual);
               double totalbeli = Double.parseDouble(rs.getString(6)) * Double.parseDouble(rs.getString(5)) - diskon;
               String txttotalbeli = String.valueOf(totalbeli);
               if(rs.getString(1).equals(cari)){
                    String data []= {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), hargajual, rs.getString(6), txtdiskon, txttotaljual, txttotalbeli};
                    model.addRow(data);
               }
              }
            }else{
              while(rs.next()){
               double hitungjual = (Double.parseDouble(rs.getString(5)) * 0.2) + Double.parseDouble(rs.getString(5));
               String hargajual = String.valueOf(hitungjual);
               double diskon = Double.parseDouble(rs.getString(5)) * 0.1;
               String txtdiskon = String.valueOf(diskon);
               double totaljual = Double.parseDouble(rs.getString(6)) * hitungjual;
               String txttotaljual = String.valueOf(totaljual);
               double totalbeli = Double.parseDouble(rs.getString(6)) * Double.parseDouble(rs.getString(5)) - diskon;
               String txttotalbeli = String.valueOf(totalbeli);
                if(rs.getString(1).equals(cari)){
                    String data []= {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), hargajual, rs.getString(6), txtdiskon, txttotaljual, txttotalbeli};
                    model.addRow(data);
                    while(rs.next()){
                       double hitungjual2 = (Double.parseDouble(rs.getString(5)) * 0.2) + Double.parseDouble(rs.getString(5));
                       String hargajual2 = String.valueOf(hitungjual2);
                       double diskon2 = Double.parseDouble(rs.getString(5)) * 0.1;
                       String txtdiskon2 = String.valueOf(diskon2);
                       double totaljual2 = Double.parseDouble(rs.getString(6)) * hitungjual2;
                       String txttotaljual2 = String.valueOf(totaljual2);
                       double totalbeli2 = Double.parseDouble(rs.getString(6)) * Double.parseDouble(rs.getString(5)) - diskon2;
                       String txttotalbeli2 = String.valueOf(totalbeli2);
                       String data2 []= {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), hargajual2, rs.getString(6), txtdiskon2, txttotaljual2, txttotalbeli2};
                       model.addRow(data2);
                       if(rs.getString(1).equals(sampe)){
                           break;
                       }
                    }
                }
             }
          } 
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        showprice();
    }//GEN-LAST:event_searchbtnActionPerformed

    private void cetakbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakbtnActionPerformed
        try{
            con.createStatement().executeUpdate("insert into grand values"+"('"+grandjual.getText()+"','"+grandbeli.getText()+"')");
            // membuat statement update pada sql untuk memasukan data ke table database
        }catch (Exception e) {
              JOptionPane.showMessageDialog(null, e.getMessage()); // menampilkan message box
           }
        try {
            int row = tabelakhir.getRowCount(); // mendeklarasikan integer row dan mengisi nya dengan jumlah baris pada jtable
            for(int i=0; i<row; i++){ // membuat loop
            // Mendeklarasikan variabel string dan mengisi nilai nya dengan nilai yang ada pada baris baris dan kolom jtable
            String kode = (String) model.getValueAt(i, 0); 
            String namabrg = (String) model.getValueAt(i, 1);
            String kodesatuan = (String) model.getValueAt(i, 2);
            String satuan = (String) model.getValueAt(i, 3);
            String hargabeli = (String) model.getValueAt(i, 4);
            String hargajual = (String) model.getValueAt(i, 5);
            String kuantitas = (String) model.getValueAt(i, 6);
            String diskon = (String) model.getValueAt(i, 7);
            String totalhargajual = (String) model.getValueAt(i, 8);
            String totalhargabeli = (String) model.getValueAt(i, 9);
            con.createStatement().executeUpdate("insert into report values"+"('"+kode+"','"+namabrg+"','"+kodesatuan+"','"+satuan+"','"+hargabeli+"','"+hargajual+"','"+kuantitas+"','"+diskon+"','"+totalhargajual+"','"+totalhargabeli+"')");
            // membuat statement update pada sql untuk memasukan data ke table database
            }
           } catch (Exception e) {
              JOptionPane.showMessageDialog(null, e.getMessage()); // menampilkan message box
           }
        
        try{
            JasperReport report; // mendeklarasikan variabel jasperreport
            String path = "C:\\Users\\Bryan\\OneDrive\\Documents\\NetBeansProjects\\UAS_32210021\\src\\View\\report1.jasper";
            // mendeklarasikan variabel string dan mendeklarasikan nya dengan alamat file jasper
            report = (JasperReport) JRLoader.loadObjectFromFile(path); // mengisi nilai report dengan jasper yang telah dibentuk
            JasperPrint Jprint = JasperFillManager.fillReport(path, null, con); // membuat jasper print dari alamat dan koneksi yang telah dibuat
            JasperViewer jviewer = new JasperViewer(Jprint, false); // mmembuat jasper view dari jasper print yang telah dibentuk
            jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE); // menutup operasi jviewer
            jviewer.setVisible(true); // menampilkan hasil dari report
        }catch (Exception e) {
              JOptionPane.showMessageDialog(null, e.getMessage()); // menampilkan message box
           }
        
         try {
            con.createStatement().executeUpdate("DELETE FROM `uas32210021`.`report`"); // membuat button print menghapus table database report
            con.createStatement().executeUpdate("DELETE FROM `uas32210021`.`grand`");  // membuat button print menghapus table database grand
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_cetakbtnActionPerformed

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        new Dashboard().setVisible(true);
        dispose();
    }//GEN-LAST:event_back1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Dimension posisi = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (posisi.width - this.getWidth())/2;
        int y = (posisi.height - this.getHeight())/2;
        this.setLocation(x, y);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back1;
    private javax.swing.JButton cetakbtn;
    private javax.swing.JTextField grandbeli;
    private javax.swing.JTextField grandjual;
    private javax.swing.JTextField inputkode;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField sampekode;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTable tabelakhir;
    // End of variables declaration//GEN-END:variables
}
